server:
  port: 8082

spring:
  application:
    name: myblog-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9oi5t6g8sgp4qqbzo.mysql.rds.aliyuncs.com:3306/myblog?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: zxx_mysql
    password: mysql_59420

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.myblog.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
