server:
  port: 8081

spring:
  application:
    name: blog-web
#  security:
#    user:
#      name: admin
#      password: 123456
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9oi5t6g8sgp4qqbzo.mysql.rds.aliyuncs.com:3306/myblog?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: zxx_mysql
    password: mysql_59420

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.zxx.blog.entity
#  configuration:
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  path: E:\Project\02.Java\03.Log
  file: service

jwt:
  header: authentication
  expiration: 7200000
  secret: zhanxx0212

upload:
  savePath: E:\Project\02.Java\04.Upload